apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
  MONGO_URL: "${MONGO_URL}"
  DATABASE_URL: "${DATABASE_URL}"
  AI_SERVICE_HOST: "${AI_SERVICE_HOST}"