---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: shashwat
spec:
  profile:
    email: svs.9494.svs_gmail.com#EXT#@svs9494svsgmail.onmicrosoft.com
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
