import sys
import os

# Fulfill architectural rules: add sibling proto directory to sys.path
sys.path.append('../proto')
# Also resolve absolute path to avoid lookup failures regardless of current working directory
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../proto')))

import time
from concurrent import futures
import grpc

import summarizer_pb2
import summarizer_pb2_grpc

class AIProtoServer(summarizer_pb2_grpc.SummarizerServicer):
    """
    High-performance gRPC server implementing the Summarizer service contract.
    """

    def SummarizeTask(self, request, context):
        """
        RPC method for analyzing and summarizing task descriptions.
        """
        start_time = time.perf_counter()
        
        # Observability: Print request details to stdout
        print(f"[AIProtoServer] Received SummarizeTask request for task_id: '{request.task_id}'")
        print(f"[AIProtoServer] Incoming payload tone: '{request.tone}', content length: {len(request.content)} chars")
        
        tone_str = request.tone if request.tone else "Standard/Professional"
        max_len_str = str(request.max_length) if request.max_length > 0 else "No limit"
        
        # Build structured markdown summary representing a mock pipeline processing
        summary_md = (
            f"# DevBoard Task Analysis & Summary\n\n"
            f"**Metadata:**\n"
            f"- **Task ID:** `{request.task_id}`\n"
            f"- **Tone:** *{tone_str}*\n"
            f"- **Target Max Length:** *{max_len_str}*\n\n"
            f"---\n\n"
            f"## Executive Summary\n"
            f"The content has been synthesized successfully with a **{tone_str}** tone.\n\n"
            f"### Content Summary\n"
            f"Here is a structured overview of the submitted payload:\n"
            f"> {request.content[:500] + ('...' if len(request.content) > 500 else '')}\n\n"
            f"### Key Insights & Observations\n"
            f"1. **Core Subject:** Analyzed payload elements cleanly.\n"
            f"2. **Styling & Structure:** Extracted key directives and consolidated them.\n"
            f"3. **Contextual Alignment:** Matched response profile to request settings.\n\n"
            f"---\n"
            f"*Generated by DevBoard AI gRPC Service.*"
        )
        
        # Simulate processing delay to mimic LLM inference (e.g., ~80ms)
        time.sleep(0.08)
        
        processing_time_ms = (time.perf_counter() - start_time) * 1000.0
        
        print(f"[AIProtoServer] Successfully parsed request and returned response for task_id: '{request.task_id}' in {processing_time_ms:.2f} ms")
        
        return summarizer_pb2.SummarizeResponse(
            task_id=request.task_id,
            summary=summary_md,
            model_version="mock-llm-1.0-devboard",
            processing_time_ms=processing_time_ms
        )

    def StreamSummarizeTask(self, request, context):
        """
        Streaming RPC placeholder handler to prevent interface implementation errors.
        """
        start_time = time.perf_counter()
        
        # Observability: Print request details to stdout
        print(f"[AIProtoServer] Received StreamSummarizeTask request for task_id: '{request.task_id}'")
        print(f"[AIProtoServer] Streaming payload tone: '{request.tone}', content length: {len(request.content)} chars")
        
        tone_str = request.tone if request.tone else "Standard/Professional"
        
        chunks = [
            f"# DevBoard Streaming Analysis\n\n",
            f"**Task ID:** `{request.task_id}` | **Tone:** *{tone_str}*\n\n",
            f"## Section 1: Introduction\nProcessing input streams asynchronously...\n\n",
            f"## Section 2: Summary\n> {request.content[:200]}...\n\n",
            f"## Section 3: Conclusion\nStreaming finished successfully.\n"
        ]
        
        for chunk in chunks:
            # Check if client has cancelled connection
            if not context.is_active():
                print(f"[AIProtoServer] Stream cancelled by client for task_id: '{request.task_id}'")
                break
                
            processing_time_ms = (time.perf_counter() - start_time) * 1000.0
            
            yield summarizer_pb2.SummarizeResponse(
                task_id=request.task_id,
                summary=chunk,
                model_version="mock-llm-1.0-devboard",
                processing_time_ms=processing_time_ms
            )
            time.sleep(0.05)
            
        print(f"[AIProtoServer] Finished streaming for task_id: '{request.task_id}'")

def serve():
    print("[AIProtoServer] Initializing DevBoard AI gRPC Server...")
    
    # Instantiate the gRPC server utilizing a ThreadPoolExecutor with 10 max workers
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    summarizer_pb2_grpc.add_SummarizerServicer_to_server(AIProtoServer(), server)
    
    # Bind the server to all network interfaces on port 50051
    bind_address = '[::]:50051'
    port = server.add_insecure_port(bind_address)
    
    print(f"[AIProtoServer] Server successfully bound to port {port} ({bind_address})")
    print("[AIProtoServer] Starting gRPC server... Listening for incoming requests...")
    
    server.start()
    
    try:
        server.wait_for_termination()
    except KeyboardInterrupt:
        print("\n[AIProtoServer] KeyboardInterrupt received. Shutting down server...")
        server.stop(grace=0)
        print("[AIProtoServer] Server stopped.")

if __name__ == '__main__':
    serve()
