# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: summarizer.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'summarizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10summarizer.proto\x12\nsummarizer\"V\n\x10SummarizeRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x12\n\nmax_length\x18\x03 \x01(\x05\x12\x0c\n\x04tone\x18\x04 \x01(\t\"h\n\x11SummarizeResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07summary\x18\x02 \x01(\t\x12\x15\n\rmodel_version\x18\x03 \x01(\t\x12\x1a\n\x12processing_time_ms\x18\x04 \x01(\x02\x32\xb4\x01\n\nSummarizer\x12N\n\rSummarizeTask\x12\x1c.summarizer.SummarizeRequest\x1a\x1d.summarizer.SummarizeResponse\"\x00\x12V\n\x13StreamSummarizeTask\x12\x1c.summarizer.SummarizeRequest\x1a\x1d.summarizer.SummarizeResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'summarizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMMARIZEREQUEST']._serialized_start=32
  _globals['_SUMMARIZEREQUEST']._serialized_end=118
  _globals['_SUMMARIZERESPONSE']._serialized_start=120
  _globals['_SUMMARIZERESPONSE']._serialized_end=224
  _globals['_SUMMARIZER']._serialized_start=227
  _globals['_SUMMARIZER']._serialized_end=407
# @@protoc_insertion_point(module_scope)
