# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import summarizer_pb2 as summarizer__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in summarizer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SummarizerStub:
    """The AI Summarization service definition.
    Facilitates high-speed gRPC communication between the FastAPI Core Backend and the Python AI Service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SummarizeTask = channel.unary_unary(
                '/summarizer.Summarizer/SummarizeTask',
                request_serializer=summarizer__pb2.SummarizeRequest.SerializeToString,
                response_deserializer=summarizer__pb2.SummarizeResponse.FromString,
                _registered_method=True)
        self.StreamSummarizeTask = channel.unary_stream(
                '/summarizer.Summarizer/StreamSummarizeTask',
                request_serializer=summarizer__pb2.SummarizeRequest.SerializeToString,
                response_deserializer=summarizer__pb2.SummarizeResponse.FromString,
                _registered_method=True)


class SummarizerServicer:
    """The AI Summarization service definition.
    Facilitates high-speed gRPC communication between the FastAPI Core Backend and the Python AI Service.
    """

    def SummarizeTask(self, request, context):
        """Analyzes and summarizes task descriptions, nested markdown, or unstructured documents.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSummarizeTask(self, request, context):
        """Optional streaming endpoint for real-time AI response streaming.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SummarizerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SummarizeTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SummarizeTask,
                    request_deserializer=summarizer__pb2.SummarizeRequest.FromString,
                    response_serializer=summarizer__pb2.SummarizeResponse.SerializeToString,
            ),
            'StreamSummarizeTask': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSummarizeTask,
                    request_deserializer=summarizer__pb2.SummarizeRequest.FromString,
                    response_serializer=summarizer__pb2.SummarizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'summarizer.Summarizer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('summarizer.Summarizer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Summarizer:
    """The AI Summarization service definition.
    Facilitates high-speed gRPC communication between the FastAPI Core Backend and the Python AI Service.
    """

    @staticmethod
    def SummarizeTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/summarizer.Summarizer/SummarizeTask',
            summarizer__pb2.SummarizeRequest.SerializeToString,
            summarizer__pb2.SummarizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSummarizeTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/summarizer.Summarizer/StreamSummarizeTask',
            summarizer__pb2.SummarizeRequest.SerializeToString,
            summarizer__pb2.SummarizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
